version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db_products
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red-app

  erp-product:
    build:
      context: ./ERP_Product
      dockerfile: Dockerfile
    container_name: erp-product
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - red-app

  erp-frontend:
    build:
      context: ./Front-Product/erp-frontend
      dockerfile: Dockerfile
    container_name: front-product
    restart: always
    depends_on:
      - erp-product
    ports:
      - "4200:80"
    networks:
      - red-app

networks:
  red-app:
    driver: bridge

volumes:
  mysql_data:
